- samples/App.jsx
- samples/charts/ChartWrapper.js
- samples/charts/css/default.css
- samples/index.js
- samples/public/index.html
- src/components/NumberChart.jsx
- src/components/PieChart.jsx
- Visual improvements for charting types
- Number chart
- UX and Visual improvements
- Node v8.0.0
- npm 5.0.0
- [Victory docs](http://formidable.com/open-source/victory/docs)
- [SVG Attribute list](https://developer.mozilla.org/de/docs/Web/SVG/Attribute)
> UX and Visual improvements for react-vizgrammer - round 2

- package-lock.json
- package.json
- samples/App.jsx
- samples/charts/BarChartConfigSample.jsx
- samples/charts/MapChartConfigSample.jsx
- samples/charts/NumberChartConfigSample.jsx
- samples/charts/PieChartsConfigSample.jsx
- samples/charts/TableChartConfigSample.jsx
- src/VizG.jsx
- src/components/BasicChart.jsx
- src/components/ChartSkeleton.jsx
- src/components/ComponentGenerator.jsx
- src/components/InlineChart.jsx
- src/components/MapChart.jsx
- src/components/NumberChart.jsx
- src/components/PieChart.jsx
- src/components/ScatterChart.jsx
fixes #20 
fixes #21 
fixes #22 
> NPM v5.3.0, Node.JS v8.5.0
> Fixes for issues #20, #21 and #22

- src/components/BasicChart.jsx
- src/components/ChartSkeleton.jsx
- src/components/ComponentGenerator.jsx
- src/components/InlineChart.jsx
- src/components/PieChart.jsx
> Fixed Sample run failure

- samples/App.jsx
- samples/charts/css/default.css
- samples/index.jsx
- src/components/ChartSkeleton.jsx
- src/components/resources/themes/victoryDarkTheme.js
- src/components/resources/themes/victoryLightTheme.js
- Fixes #28 
- move inline styling to themes that can be dynamically changed
- will also be compatible with material-ui's dynamic theming
- Node v8.0.0
- npm 5.0.0
- [victory theming](https://formidable.com/open-source/victory/guides/themes)
> Theme implementations for charting

- src/components/ComponentGenerator.jsx
- src/components/MapChart.jsx
- src/components/PieChart.jsx
Replace the legend component in pie chart from the one written in the ComponentGenerator.jsx
> Node.JS v8.5.0, NPM v5.3.0
> Fix legend component in Pie Chart

- package.json
- Bumping NPM package version to 0.6.2 
- Added git repository info to the package.json
> Bumping npm package version 0.6.2

- src/components/ComponentGenerator.jsx
Change the width of the widget container to 20% of the container width
> Changed the legend width to 20%

- README.md
- package-lock.json
- package.json
- samples/charts/MapChartConfigSample.jsx
- samples/index.jsx
- src/VizG.jsx
- src/components/BasicChart.jsx
- src/components/ChartSkeleton.jsx
- src/components/ComponentGenerator.jsx
- src/components/InlineChart.jsx
- src/components/MapChart.jsx
- src/components/NumberChart.jsx
- src/components/PieChart.jsx
- src/components/ScatterChart.jsx
- src/components/TableChart.jsx
Fixed the issue of chart not responsive for changes in container height 
> Fix for the issue #34

- src/components/BasicChart.jsx
- src/components/helper.js
> Implement a sorting to Linear scale and Time Scale charts

- src/VizG.jsx
Add an attribute to the chart configuration to give the ability to change whether the chart should append data or not.
> Added attribute append to the chart configs

- README.md
- src/components/MapChart.jsx
- src/components/TableChart.jsx
- Fixed scaling factors of Map Charts.
- Fixed metadata checking of Map Charts and Table Charts
> Fixing Some minor bugs in Map Charts and Table Charts

- package-lock.json
- package.json
- src/components/ChartSkeleton.jsx
- src/components/ComponentGenerator.jsx
resolves #44 
resolves #45 
Node.JS v8.5.0, npm v5.3.0
> Removed victory portal from Line Charts and Area Charts

- src/components/BasicChart.jsx
- src/components/ChartSkeleton.jsx
- src/components/ComponentGenerator.jsx
- src/components/PieChart.jsx
- src/components/ScatterChart.jsx
resolves #46 
Node.JS v8.3.0, NPM v 5.3.0
> Embedding legend inside the victory chart component

- docs/index.html
setup gh-pages to be published from the master branch
> Add gh-pages docs directory

- .npmignore
- package-lock.json
- package.json
- src/components/BasicChart.jsx
- src/components/ChartSkeleton.jsx
- src/components/ComponentGenerator.jsx
Fixing css padding properties to fix overlapping of bar charts
> Updating Styling of the charts

- samples/App.jsx
- samples/chart-docs/AreaChartSamples.jsx
- samples/chart-docs/BarChartSamples.jsx
- samples/chart-docs/GeographicalChartsSample.jsx
- samples/chart-docs/LineChartSamples.jsx
- samples/chart-docs/NumberChartSample.jsx
- samples/chart-docs/PieChartSamples.jsx
- samples/chart-docs/ScatterPlotSample.jsx
- samples/chart-docs/TableChartSamples.jsx
- samples/index.jsx
- Added meaningful titles for samples in view usage pages.
- Added a new set of samples for spark-charts
> Sample Improvements

- package-lock.json
- package.json
- src/VizG.jsx
Previously users were able to update whether to append new data or not by the props given to the react component and also by the chart configuration this will only allow users to manage that only from the chart configuration
resolves #50 
> Removed append prop from the charts

- src/ErrorBoundary.jsx
- src/VizG.jsx
- src/components/ArcCharts.jsx
- src/components/AreaChart.jsx
- src/components/BarChart.jsx
- src/components/BaseChart.jsx
- src/components/ChartContainer.jsx
- src/components/ComposedChart.jsx
- src/components/InlineChart.jsx
- src/components/LegendComponent.jsx
- src/components/LineChart.jsx
- src/components/NumberChart.jsx
- src/components/ScatterPlot.jsx
- src/components/TableChart.jsx
- src/components/helper.js
resolves #4 
resolves #15 
Node v8.8.1, NPM v5.4.2
> Chart tooltip visual improvements and Added doc comments for the Charts

- samples/GettingStarted.jsx
- samples/chart-docs/SimpleChart.jsx
Visual Improvements for Get started page
> Visual Improvements for Get Started page

- README.md
Update to the Readme file on starting samples with the changes introduced with #68
> Update for the README file on starting the samples

- package-lock.json
- package.json
- src/components/ArcCharts.jsx
- src/components/BaseChart.jsx
- src/components/ChartContainer.jsx
Improvements for Pie Chart Legend Padding so that it won't overlap with the Chart when the chart size gets smaller.
Node.JS v8.8.1, NPM 5.4.2
> Imporvements for Pie Chart Legend Padding.

- package-lock.json
- package.json
- samples/App.jsx
- samples/chart-docs/TableChartSamples.jsx
- src/components/BaseChart.jsx
- src/components/TableChart.jsx
- src/components/resources/css/tableChart.css
Current implementation doesn't allow configuration of color based categorization column by column when applied through the configuration it will be applied for the whole Table Chart like shown below
```javascript
{
"charts": [
{
"type": "table",
"columns": [
"EngineType",
"torque",
"rpm"
],
"columnTitles": [
"Engine Type",
"Engine Torque",
"Engine RPM"
]
}
],
"maxLength": 7,
"colorBasedStyle": true
}
```
With this the table chart will allow users to individually configure color based categorizing for columns.
```javascript
{
"charts": [
{
"type": "table",
"columns": [
{
"name": "EngineType",
"title": "EngineType",
"colorBasedStyle": true
},
{
"name": "torque",
"title": "Engine Torque"
},
{
"name": "rpm",
"title": "Engine RPM",
"colorBasedStyle": true,
"colorScale": [
"red"
]
}
]
}
], …
```
> Implement Table Chart color categorizing for each individual column

- README.md
Include gh-pages link in the README.md
> Include gh-pages link in the README.md

- package-lock.json
- package.json
- src/components/TableChart.jsx
Implement onClick event handling for Table Chart
```jsx
function handleOnClick(evt, rowInfo) {
// function logic
}
<VizG metadata={...} data={...} config={...} onClick={handleOnClick}>
```
https://github.com/react-tools/react-table#props
> Implement onClick event handling for Table Chart

- package-lock.json
- package.json
- samples/chart-docs/TableChartSamples.jsx
- src/components/TableChart.jsx
Implement pagination for Table chart
```jsx
{
"charts": [
{
"type": "table",
"columns": [
{
"name": "EngineType",
"title": "EngineType",
"colorBasedStyle": true
},
{
"name": "torque",
"title": "Engine Torque"
},
{
"name": "rpm",
"title": "Engine RPM",
"colorBasedStyle": true,
"colorScale": [
"red"
]
}
]
}
],
"maxLength": 7,
"colorBasedStyle": true,
"pagination": true
}
```
https://github.com/react-tools/react-table/blob/master/README.md
> Implement Pagination for Table Chart

- package-lock.json
- package.json
- samples/chart-docs/TableChartSamples.jsx
- src/components/TableChart.jsx
As per the discussion on #92 this PR will change the property value to 'uniquePropertyColumn'
Node.JS v8.8.0, NPM v5.4.2
> Rename configuration property 'deduplicationColumn' of Table chart to 'uniquePropertyColumn'

- package-lock.json
- package.json
- src/components/ArcCharts.jsx
- src/components/BaseChart.jsx
- src/components/MapChart.jsx
- src/components/ScatterPlot.jsx
- src/components/TableChart.jsx
This PR will clean the JSON Object returned from the onClick events of the charts and the JSON will only contain data related to the clicked data point.
Node.js v8.8.1, NPM v5.4.2
> Clean the JSON objects returned from the onClick events

- package-lock.json
- package.json
- samples/chart-docs/TableChartSamples.jsx
- samples/chart-docs/util/MakeData.js
- src/components/TableChart.jsx
This will allow users to filter data that are in the Table Chart
configuration to get the filtering option:
```javascript
{
charts: [
{
type: 'table',
columns: [
// column configurations
],
},
],
filterable: true,
}
```
> Add filterable option Table charts

- package-lock.json
- package.json
- src/components/ArcCharts.jsx
- src/components/MapChart.jsx
- src/components/TableChart.jsx
- Improvements for Data returned from Click events for Pie Charts, Map Charts
- Visual improvements for Table Charts user selected rows are highlighted.
> Improvements for Data returned on Click events and Visual improvements for Table charts

- package-lock.json
- package.json
- samples/chart-docs/NumberChartSample.jsx
- samples/chart-docs/TableChartSamples.jsx
- src/components/NumberChart.jsx
- src/components/TableChart.jsx
- src/components/resources/css/tableChart.css
- Style improvements for Table Charts
- Fixes #89 
> Style Improvments for Table charts and Fix for #89

- package-lock.json
- package.json
- src/components/ChartContainer.jsx
> Fix chart axis not updating in ordinal series Bar Chart

- package-lock.json
- package.json
- samples/chart-docs/BarChartSamples.jsx
- src/components/BarChart.jsx
- src/components/BaseChart.jsx
- src/components/util/Constants.js
- Introduce `timeStep` attribute to Time series bar chart configuration
- Introduce `linearSeriesStep` attribute to linear series bar chart configuration
- improvements for bar width calculation of Bar charts
> Improvement for Bar width calculation of Time series bar charts and linear series bar Charts

- package-lock.json
- package.json
- src/components/ChartContainer.jsx
> Add missing validation for the xAxis of ordinal bar charts

- package-lock.json
- package.json
- src/components/BarChart.jsx
> Fix issue with color categorization of Bar chart

- package-lock.json
- package.json
- samples/chart-docs/PieChartSamples.jsx
Update title and colors of Percentage chart
fixes: #111
>  Update title and colors of Percentage chart

- samples/GettingStarted.md
> Add onClick event sample for documentation

- src/components/ChartContainer.jsx
Fix tick label length issue
Fixes: #122
Node.JS v6.11.2, NPM v5.7.1
>  Fix tick label length issue

- src/components/BarChart.jsx
- src/components/ChartContainer.jsx
Fix bar chart tooltip and allow domain values to be user configurable
Fixes: #121, #115
> Fix bar chart tooltip and allow domain values to be user configurable

- samples/chart-docs/TableChartSamples.jsx
- samples/chart-docs/TableChartServerSidePagination.jsx
Fix theme not applying to Table Chart documentation
> Theme fix in Documentation

- package-lock.json
- package.json
- src/components/ChartContainer.jsx
> Add validation for function that shortens tick values

- package-lock.json
- package.json
- samples/chart-docs/TableChartSamples.jsx
- src/components/TableChart.jsx
Support match data and highlight cells
>  Support match data and highlight cells

- package-lock.json
- package.json
- samples/chart-docs/PieChartSamples.jsx
- src/components/ArcCharts.jsx
Add Pie Chart legend disable functionality
Fixes: #150 
Updated
Node.JS v6.11.2, NPM v5.7.1
>  Add Pie Chart legend disable functionality

- package-lock.json
- package.json
- src/components/BarChart.jsx
Fix one data point overlap x axis
Fixes: #157 
This is an issue with victory library and we need to upgrade it. For the time being as a workaround reduced the bar width.
Node.JS v6.11.2, NPM v5.7.1
>  Fix one data point overlap x axis

- package-lock.json
- package.json
- src/components/BarChart.jsx
Fix bar chart yAxis overlap for one data point
Fixes: https://github.com/wso2/product-sp/issues/686
Node.JS v8.8.1, 
NPM v5.7.1
>  Fix bar chart yAxis overlap for one data point

- dist/components/resources/css/tableChart.css
- package-lock.json
- package.json
- src/components/TableChart.jsx
- src/components/resources/css/tableChart.css
Fixes: #164 
Node.JS v8.8.1,
NPM v5.7.1
>  Fix table row height

- package-lock.json
- package.json
- samples/chart-docs/NumberChartSample.jsx
- src/components/NumberChart.jsx
Fix number chart height
Fixes: #166
>  Fix number chart height

- package-lock.json
- package.json
- src/VizG.jsx
- src/components/TableChart.jsx
> Table height issue

- package-lock.json
- package.json
- samples/chart-docs/AreaChartSamples.jsx
- samples/chart-docs/BarChartSamples.jsx
- samples/chart-docs/LineChartSamples.jsx
- samples/chart-docs/PieChartSamples.jsx
- src/components/LegendComponent.jsx
Add config to set vertical offset to legend
Fixes: #170 
Node.JS v8.8.1,
NPM v5.7.1
>  Add config to set vertical offset to legend

- package-lock.json
- package.json
- src/components/LegendComponent.jsx
> Fix legend text color not changing on theme change

- package.json
- src/components/ArcCharts.jsx
- src/components/AreaChart.jsx
- src/components/BarChart.jsx
- src/components/ChartContainer.jsx
- src/components/ComposedChart.jsx
- src/components/CustomLegend.jsx
- src/components/LegendComponent.jsx
- src/components/LineChart.jsx
> Fix legend column white space

- package.json
- src/components/ArcCharts.jsx
- src/components/AreaChart.jsx
- src/components/BarChart.jsx
- src/components/ChartContainer.jsx
- src/components/CustomXaxisLabel.jsx
- src/components/LineChart.jsx
- src/components/ScatterPlot.jsx
Automate tick angle if the tick values are too long
Fixes: #198 #197
> Automate tick angle and issue fixes

- package.json
- src/components/ChartContainer.jsx
- src/components/LegendComponent.jsx
> Fix pie chart height

- package.json
- src/components/ChartContainer.jsx
- src/components/CustomYaxisLabel.jsx
Trim Y axis tick labels
Fixes: #202
>  Trim Y axis tick labels

- README.md
> Improve documentation
> It fix mainly typos
> Docs typos

- package.json
- src/components/ChartContainer.jsx
Fix horizontal bar chart tick angle issue
>  Fix horizontal bar chart tick angle issue

- package.json
- src/components/ArcCharts.jsx
- src/components/AreaChart.jsx
- src/components/BarChart.jsx
- src/components/ChartContainer.jsx
- src/components/CustomLegend.jsx
- src/components/LegendComponent.jsx
- src/components/LineChart.jsx
- src/components/ScatterPlot.jsx
>  Fix legend tooltip trim issue

- src/components/ComposedChart.jsx
- src/components/CustomXaxisLabel.jsx
- src/components/ScatterPlot.jsx
> Fix formatting

- src/components/BarChart.jsx
- src/components/LegendComponent.jsx
- src/components/resources/css/tableChart.css
> Fix code formatting

- package.json
- samples/chart-docs/TableChartSamples.jsx
- samples/chart-docs/TableChartServerSidePagination.jsx
- src/components/Pagination.jsx
- src/components/TableChart.jsx
This PR adds a config to hide/show total pages count in the table pagination UI component. The config is considered as false by default.
> Add support to hide total page count in table pagination UI component
