wso2/react-vizgrammar

- src/components/BasicChart.jsx
- src/components/ChartSkeleton.jsx
Fixed the issue of X -axis ticks appearing as numbers when an ordinal X value is given
make the corresponding ticks appear in that scenario
> NPM v5.3.0, Node.js v8.5.0
> Fixed issue of appearing numbers in the X - axis when ordinal data type is provided

- src/components/ChartSkeleton.jsx
Currently the users can't change the color of the grid that's rendered behind the chart and from this users can add the attribute 'gridColor' to the chart attribute and change the color of it
> NPM v5.3.0, Node.js v8.5.0
> Expose grid color of the charts through the chart configuration

- src/components/ChartSkeleton.jsx
When formatting tick labels in the previous case getting values with decimals for the tick values wasn't considered this will fix getting errors that will occur in the case of containing tick values with decimals.
> Handle decimal values in ordinal tick formatting for bar charts

- src/components/BasicChart.jsx
- src/components/ComponentGenerator.jsx
Give the user to define the format of the time displayed in the tool tip in the chart configuration
introduce a new attribute in the chart configuration 'tipTimeFormat' and for it's value user should give a regex pattern that's defined in d3 [timeFormat](https://github.com/d3/d3-time-format/blob/master/README.md#locale_format) function
NPM v5.3.0, Node v8.5.0
> Add tool tip formatting for time series charts

- src/components/ChartSkeleton.jsx
- src/components/InlineChart.jsx
There was an error popping up when visualizing ordinal series graphs related to tick count of the axis that issue was fixed here.
NPM v5.3.0, NodeJS v8.5.0
> Fixed the tick count issue in the ordinal series charts

- package-lock.json
- package.json
- samples/charts/AreaChartConfig.jsx
- samples/charts/PieChartsConfigSample.jsx
- samples/index.jsx
- src/VizG.jsx
- src/components/BasicChart.jsx
- src/components/ComponentGenerator.jsx
- src/components/InlineChart.jsx
- src/components/MapChart.jsx
- src/components/NumberChart.jsx
- src/components/PieChart.jsx
- src/components/ScatterChart.jsx
- src/components/TableChart.jsx
Currently apart from configuration metadata is the most important set of information to  plot a graph. if it's not there, the chart will throw errors and this PR will fix that issue
> Added a checking for whether the metadata prop is defined in the Chart

- src/components/ComponentGenerator.jsx
- src/components/InlineChart.jsx
- src/components/PieChart.jsx
- Exposed fontSize of the Percentage chart as 'labelFontSize' into the config
- Exposed strokeWidth of the Inline Area and Line charts to the config as 'strokeWidth'
- Exposed the fillOpacity of the Inline Area charts to the config as 'fillOpacity'
> Exposing some of the hard-coded styles in Percent charts and Inline Charts

- package-lock.json
- package.json
- src/components/ScatterChart.jsx
Earlier user was required to give scatter plot metadata all in lower case with this fix it will ignore the case for metadata.
> Fixed the case sensitivity of Scatter plots Metadata

- src/VizG.jsx
- src/components/ChartSkeleton.jsx
- src/components/ScatterChart.jsx
Previously scatter chart tooltip included color and size attributes even though they were not included in the config this will fix that and will only show attributes defined in the chart config
> Tooltip improvements for scatter charts

- src/components/ChartSkeleton.jsx
Moved axis label of the y axis to the top of the chart instead of the side.
resolves wso2/carbon-analytics#949
Node.JS v8.9.4, NPM v5.6.0
> fixed axis label position

- src/components/BaseChart.jsx
> Set chart config at the initial graph render time
> This fixes events  like `onClick()` failures before a re-render of the graph take place. 
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Set chart config at the initial graph render

- package-lock.json
- package.json
- samples/App.jsx
- samples/chart-docs/PieChartSamples.jsx
- samples/styles/snippet-highlight.css
- src/components/ArcCharts.jsx
Add semi circle option to Pie Charts
Added to samples
> Add semi circle option to Pie Charts

- package-lock.json
- package.json
- src/components/BarChart.jsx
- src/components/ChartContainer.jsx
Bug fix for Bar width calculation in a time series Bar chart which uses the property `timeStep`.
In the version 0.7.16 and later the bars of a time series created with use of `timeStep` property would overlap with each other due to a problem in the calculation of the barWidth
```jsx
this.ordinalDataChart = {
x: 'Quarter',
charts: [
{
type: 'bar',
y: 'Sales',
color: 'Product',
mode: 'stacked',
},
],
legend: true,
timeStep: 'year',
};
this.timeMetadata = {
names: ['Quarter', 'Sales', 'Product'],
types: ['time', 'linear', 'ordinal'],
};
this.timeData = [
[1420050600000, 100000, 'Product 1'],
[1451586600000, 14000, 'Product 1'],
[1483209000000, 110000, 'Product 1'],
[1514745000000, 240000, 'Product 1'],
];
```
The above configuration would render the following.
This PR will fix the issue in …
> Fix Bar width calculation bug in time series bar charts

- samples/chart-docs/BarChartSamples.jsx
- src/components/BarChart.jsx
> Bar Chart is displaying Y axis ticks as `Double`, even when we pass an integer for the Y axis. 
> X Axis values also shown as `Double` values, for integers too.
> Display tick values in the format of integer when user prefers. Otherwise, show doubles values.
Which will show `Integer` values for the ticks, if the attribute values is set to `"Int"`. Otherwise it will show `Double` values.
> N/A
> N/A
> Added 2 new Attributes to `ChartConfigs` in Bar Chart.
* `yAxisNumberType`
* `xAxisNumberType`
If the `yAxisNumberType` is set to `"Int"`, it will show `Integer` values in the Y Axis ticks. 
If the `xAxisNumberType` is set to `"Int"`, it will show `Integer` values in the X axis ticks.
> Docs in the Samples are updated, added two new attributes in the chart configs.
> N/A
> N/A
> N/A
- N/A
- …
> Adding new attributes for Bar Chart config, to display Integers as tick values.

- samples/chart-docs/BarChartSamples.jsx
- src/components/BarChart.jsx
> Previously if the user need to show tip values as `integer`s they had to add an attribute in the configs. But if the values are actually `integer`s we should show them as integers by default.
> Now, if the value of the tip is an `integer`, the tip value will be shown as an `integer`. If the value is a `double`, tip value will show the `double` value.
> New check is added to check the value passed to tip, and if the value is an `integer`, `integer` value is shown. Otherwise, `double` value is shown.
> N/A
> Removed the two config attributes, 
* `xAxisNumberType`
* `yAxisNumberType`
> Sample documentation is updated.
> N/A
> N/A
> N/A
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and …
> Changing Bar chart tip to show integer values if the values are integers

- src/components/AreaChart.jsx
> Area chart tip values are shown as `Double` values, even if they're `int`s. If the values is an `int`, chart tip value should be shown as an `int`.
> To show tip value as an `int`, if the value is an `int`. Otherwise show `Double` value.
> Now the chart will check whether the value is an `int` first, and if so, it will show tip value as an `int`. If it is not an `int`, the `double` value will be shown.
> N/A
> N/A
> N/A. This is the expected behavior. 
> N/A
> N/A
> N/A
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> …
> Changing Area chart tip to show integer values if the values are integers

- src/components/TableChart.jsx
Table chart filter does not filter data if the filtering text containing upper case letters. This will fix that issue.
> Fixes #138
> Fixing table chart filtering issue

- package-lock.json
- package.json
- samples/chart-docs/GeographicalChartsSample.jsx
- src/components/MapChart.jsx
fixes #135 
This will introduce two separate properties to define the colorScale value range for the chloropeth map and will remove the property `chloropethValueRange`
new properties to define the chloropeth map color scale range,
- `chloropethRangeUpperBound` - Define the upper bound of the range if only this property is defined the lower bound will be calculated based on the data provided
- `chloropethRangeLowerBound` - Define the lower bound of the range if only this property is defined the upper bound will be calculated based on the data provided
> Introduce properties to define upper and lower bounds of the colorscale of the chloropeth map seperately

- src/components/BarChart.jsx
Currently the for ordinal series bar charts the xAxis values get sorted automatically this PR include the Fix to prevent that and show them according to the order of data input
> Fix automatic sorting of xAxis values in ordinal bar charts

- package-lock.json
- package.json
- samples/chart-docs/TableChartSamples.jsx
- samples/chart-docs/TableChartServerSidePagination.jsx
- samples/chart-docs/util/MakeData.js
- src/VizG.jsx
- src/components/TableChart.jsx
fixes #140 
The PR will introduce Server-Side pagination for the table charts. Once the server-side pagination is enabled user will have to handle the incoming data(sorting etc.) manually using a REST API or any other method. To enable the functionality 3 new props will be introduced to the React component
- `manual` - Boolean value to indicate that the user will be handling the data of the chart(sorting etc.)
- `pages` - Total number of pages in the table chart
- `onFetchData` - Function to be executed on click event of next/previous button of the pagination and at the loading time
The prop will accept a function with one parameter, During the execution this parameter will contain the state object related to the table chart. To retrieve data refer the following attributes of the state …
> Add server-side pagination for Table Charts

- package-lock.json
- package.json
- src/components/ChartContainer.jsx
- src/components/LegendComponent.jsx
Currently the legend if the legend text is too long it will cut through the chart as shown below
This PR will introduce the configuration `legendTextBreakLength` to break the length of the legend text
> Add line breaking option when the Legend text length is too long

- dist/components/resources/css/tableChart.css
- src/components/TableChart.jsx
- src/components/resources/css/tableChart.css
> Dark theme styles are not applied for filter-search and filter-search-container in table chart. 
>No minimum width is set to the filter-search.
> darkTheme and LightTheme classes added according to the props.theme
>min-width set for the filter-search
>Node.JS v8.11.4,
>NPM v5.6.0
> Fix TableChart filter-search styling

- samples/chart-docs/TableChartSamples.jsx
- samples/chart-docs/TableChartServerSidePagination.jsx
- src/components/TableChart.jsx
Allow users to enable or disable sorting for Table Chart
Updated
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Add sortable option to Table Chart

- samples/App.jsx
- src/components/BaseChart.jsx
- src/components/ChartContainer.jsx
- src/components/ScatterPlot.jsx
>In the bar chart if the dataset is not changing and the class which contains the bar chart triggers a state change, It will duplicate the data into the datasets. This will cause to recalculate the bar width according to the new dataset width
>Currently scatter plot chart is not able to consume ordinal values for the color category. Chart will not be previewd if an ordinal column name provided under the configuration
> Resolve the issue :  #183 #178  #188
#183 - before 
#188 - before
> Ubuntu 18.04
>Node : 8.8.1
>npm : 5.4.2
> Fix for merging same data for dataset

- samples/chart-docs/GeographicalChartsSample.jsx
- src/components/ArcCharts.jsx
- src/components/AreaChart.jsx
- src/components/BarChart.jsx
- src/components/ChartContainer.jsx
- src/components/ComposedChart.jsx
- src/components/CustomLegend.jsx
- src/components/LegendComponent.jsx
- src/components/LineChart.jsx
- src/components/MapChart.jsx
- src/components/ScatterPlot.jsx
- src/components/resources/themes/victoryDarkTheme.js
- src/components/resources/themes/victoryLightTheme.js
Fix legend styles according to width, height and number of legend items
Fixes: #179 #151
If the legend items are greater than available height, legend will be shown at the bottom with with multiple columns spanning available width.
If the label length is more that 16 character long it will trim from the middle and full text is shown in a tooltip. 
Updated
* Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
* Ran FindSecurityBugs plugin and verified report? yes
* Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Fix legend styles according to width, height and number of legend items

- src/components/ArcCharts.jsx
> The arc chart tooltip contains only the percentage value not the actual count: Resolves #186 
> Add the numerical value to the tool tip
> Previously
>After
> If a user needs to view the count or the percentage he can view using the tooltip. And if the percentage does not contain decimal values it will omit the decimal point.
> Ubuntu 18.04
Node : 8.8.1
npm : 5.4.2
> Fix for not showing value in the Arc chart  tooltip

- src/components/AreaChart.jsx
- src/components/BarChart.jsx
- src/components/LineChart.jsx
- src/components/ScatterPlot.jsx
> Pass the props to the onClick method: Resolves #193
> adding arrow function which will take the props and pass down that to the onclick method
> Fix for not passing props from the chart for onClick function

- package.json
- src/components/ChartContainer.jsx
- src/components/CustomXaxisLabel.jsx
- src/components/CustomYaxisLabel.jsx
Resolves 
https://github.com/wso2/analytics-apim/issues/1300
https://github.com/wso2/analytics-apim/issues/1248
https://github.com/wso2/analytics-apim/issues/966
This PR introduces a new configuration "ignoreYaxisDecimalPoints" which can be used to drop the decimal point ticks from the y axis and use only counting numbers.
> Add ability to hide decimal points based on a config
